### ISSUE TITLE
source url unavailable

### ISSUE THREAD

**Issue by teto** [lunarmodules/lua-iconv#8]
the download link in the rockspec https://github.com/ittner/lua-iconv/blob/b761918588736348698eb060a3a490f448786f01/lua-iconv-7-1.rockspec#L9C10-L9C74 is a 404. It breaks my script that autogenerates nix code. 

Is it possible to fix the rockspec to point at an existing archive ?

**Comment by alerque** [comment]
The source URL is completely bogus inside the rockspec. It could be re-issued as a rockrel 2 with a valid URL, but I think we're immanently going to overhaul the rockspec a little bit to better match others in this org and the automatic publishing process. That will include using Git based URLs that use a branch for the dev rockspec and tags for the released ones. Maybe once that tooling is spun up (with no other changes) we should cut a new rockrel bump release.

Are there any substantive changes since 7 already in the repo?

Speaking of, can we switch to something resembling semver, say `v7.0.0-1` for the next release?

**Comment by teto** [comment]
It's all good for me, I just care about fixing the rockspec so I can complete https://github.com/NixOS/nixpkgs/pull/258819.  Now that @ittner is responsive, he may have a different opinion ?
